# Generated by Django 5.0.3 on 2025-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimg',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
    ]
