# Generated by Django 5.0.3 on 2025-11-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
